### ISSUE TITLE
bug toscaparser

### ISSUE THREAD

**Issue by lucarin91** [di-unipi-socc/TosKer#20]
```
  mysql_container:
      type: tosker.docker.container.persistent
      ...
      requirements:
        - attach:
            node: mysql_volume
            relationship:
              type: tosca.relationships.AttachesTo
              properties:
                location: /var/lib/mysql
```
 the type in the relation template have to be optional, but the validetor of the toscaparser throw an error say that is required.

reference: http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/cos01/TOSCA-Simple-Profile-YAML-v1.0-cos01.html#DEFN_ELEMENT_REQUIREMENT_ASSIGNMENT
